moviedb/blueprints/root.py
from flask import Blueprint, render_template

bp = Blueprint('root',
               __name__,
               url_prefix='/')

@bp.route('/')
@bp.route('/index')
def index():
    return render_template("root/index.jinja2",
                           title="página principal")

moviedb/templates/base.jinja2
{% from 'bootstrap5/utils.html' import render_icon %}
{% from 'navbar.jinja2' import barra_navegacao with context %}
<!doctype html>
<html lang="pt-BR">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {{ bootstrap.load_css() }}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}">
        {% block styles %}
        {% endblock %}
        {% if title %}
            <title>{{ title }}</title>
        {% else %}
            <title>{{ app_config["APP_NAME"] }}</title>
        {% endif %}
    {% endblock %}
</head>
<body id="page-top" class="d-flex flex-column min-vh-100 mx-2 mt-3">
{{ barra_navegacao() }}
{% if jumbo %}
    <div class="my-5">
        <div class="p-5 text-center bg-body-tertiary">
            <div class="container py-5">
                <h1 class="text-body-emphasis">{{ jumbo }}</h1>
            </div>
        </div>
    </div>
{% endif %}

<main id="content" class="px-5">
    <div class="container-fluid">
        {% block content %}{% endblock %}
    </div>
</main>

<footer class="mt-auto pt-5 mt-5 bg-body-tertiary text-body-secondary">
    <div class="container-fluid pb-4 px-5">
        <div class="row">
            <div class="col">
                <img class="me-3 float-start" src="{{ url_for('static', filename='img/if.svg') }}"
                     alt="Logotipo do IFSP" width="40"/>
                <p class="fs-tiny text-start"><em>Aplicação desenvolvida no escopo
                    da disciplina "Desenvolvimento Web II" do
                    <a href="https://sjp.ifsp.edu.br/cursos-tecnicos/221-curso-tecnico-em-informatica"
                       target="_blank">Curso Técnico em Informática</a> do Instituto Federal de
                    Educação, Ciência e Tecnologia de São Paulo,
                    <a href="https://sjp.ifsp.edu.br/" target="_blank">campus São José do Rio
                        Preto</a>,
                    durante o segundo semestre de 2025</em>
                </p>
            </div>
            <div class="col text-end ms-auto">
                <div class="d-md-none ms-3">
                    <a class="d-inline scroll-to-top"
                       href="#page-top">{{ render_icon('arrow-bar-up', size=16) }}</a>
                </div>
                <div class="d-none d-md-inline">
                    <a class="d-inline scroll-to-top"
                       href="#page-top">{{ render_icon('arrow-bar-up', size=32) }}</a>
                </div>
            </div>
        </div>
    </div>
</footer>
{{ bootstrap.load_js() }}
{% block scripts %}
{% endblock %}
</body>
</html>

moviedb/templates/layout.jinja2
{% from 'bootstrap5/utils.html' import render_icon %}
{% from 'navbar.jinja2' import barra_navegacao with context %}
{% from 'utils.jinja2' import render_messages with context %}
<!doctype html>
<html lang="pt-BR">
<head>
    {% block head %}
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        {{ bootstrap.load_css() }}
        <link rel="stylesheet" href="{{ url_for('static', filename='css/site.css') }}">
        {% block styles %}
        {% endblock %}
        <title>
        {{ app_config["APP_NAME"] }}
        {% if title %}
            - {{ title }}
        {% endif %}
        </title>
    {% endblock %}
</head>
<body id="page-top" class="d-flex flex-column min-vh-100 mx-2 mt-3">
{{ barra_navegacao() }}
{{ render_messages() }}
{% if jumbo %}
    <div class="my-5">
        <div class="p-5 text-center bg-body-tertiary">
            <div class="container py-5">
                <h1 class="text-body-emphasis">{{ jumbo }}</h1>
            </div>
        </div>
    </div>
{% endif %}



<main id="content" class="px-2">
    <div class="container-fluid">
        {# bread_crumb() #}
        <div class="row justify-content-center">
            <div class="{%- block card_col -%}col-12{%- endblock -%}">
                <div class="card shadow-lg my-5">
                    <div class="card-header px-5 py-4">
                        {%- block content_header -%}
                            {% if title and not title_card %}
                                <h2 class="fw-bold mb-4 card-title">{{ title }}</h2>
                            {% else %}
                                {% if title_card %}
                                    <h2 class="mb-4 card-title">{{ title_card }}</h2>
                                {% endif %}
                                {% if subtitle_card %}
                                    <p class="fst-italic card-subtitle text-body-secondary">{{ subtitle_card }}</p>
                                {% endif %}
                            {% endif %}
                        {%- endblock -%}
                    </div>
                    <div class="card-body p-3">
                        {% block content %}{% endblock %}
                    </div>
                    <div class="card-footer justify-content-center p-3 overflow-auto">
                        {% block footer %}{% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>




<footer class="mt-auto pt-5 mt-5 bg-body-tertiary text-body-secondary">
    <div class="container-fluid pb-4 px-5">
        <div class="row">
            <div class="col">
                <img class="me-3 float-start" src="{{ url_for('static', filename='img/if.svg') }}"
                     alt="Logotipo do IFSP" width="40"/>
                <p class="fs-tiny text-start"><em>Aplicação desenvolvida no escopo
                    da disciplina "Desenvolvimento Web II" do
                    <a href="https://sjp.ifsp.edu.br/cursos-tecnicos/221-curso-tecnico-em-informatica"
                       target="_blank">Curso Técnico em Informática</a> do Instituto Federal de
                    Educação, Ciência e Tecnologia de São Paulo,
                    <a href="https://sjp.ifsp.edu.br/" target="_blank">campus São José do Rio
                        Preto</a>,
                    durante o segundo semestre de 2025</em>
                </p>
            </div>
            <div class="col text-end ms-auto">
                <div class="d-md-none ms-3">
                    <a class="d-inline scroll-to-top"
                       href="#page-top">{{ render_icon('arrow-bar-up', size=16) }}</a>
                </div>
                <div class="d-none d-md-inline">
                    <a class="d-inline scroll-to-top"
                       href="#page-top">{{ render_icon('arrow-bar-up', size=32) }}</a>
                </div>
            </div>
        </div>
    </div>
</footer>
{{ bootstrap.load_js() }}
{% block scripts %}
{% endblock %}
</body>
</html>

moviedb/templates/navbar.jinja2
{% macro barra_navegacao() %}
    {% from 'bootstrap5/nav.html' import render_nav_item %}
    {% from 'bootstrap5/utils.html' import render_icon %}
    <nav class="navbar navbar-expand-sm bg-primary-subtle rounded-4 shadow-sm mb-3 px-3 py-2 sticky-top">
        <div class="container-fluid">
            <a class="navbar-brand ps-3"
               href="{{ url_for('root.index') }}">{{ render_icon('film', size=60) }}&nbsp;&nbsp;{{ app_config["APP_NAME"] }}</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                            {{ render_icon('film') }} Filmes
                        </a>
                        <ul class="dropdown-menu dropdown-menu-lg-end">
                            <li><a class="dropdown-item" href="#">Submenu</a></li>
                            <li><a class="dropdown-item" href="#">Submenu</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li><a class="dropdown-item" href="#">Submenu</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                            {{ render_icon('people-fill') }} Pessoas
                        </a>
                        <ul class="dropdown-menu dropdown-menu-lg-end">
                            <li><a class="dropdown-item" href="#">Submenu</a></li>
                            <li>
                                <hr class="dropdown-divider">
                            </li>
                            <li><a class="dropdown-item" href="#">Submenu</a></li>
                            <li><a class="dropdown-item" href="#">Submenu</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown ms-3">
                        <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown">
                            {% if current_user.is_anonymous %}
                                <span class="fw-semibold">Acesso ao sistema</span>
                            {% else %}
                                <span class="fw-semibold">{{ current_user.email }}</span>
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu dropdown-menu-lg-end">
                            {% if current_user.is_authenticated %}
                                <li><a class="dropdown-item" href="#">{{ render_icon('person') }}&nbsp;Perfil</a> </li>
                                <li><a class="dropdown-item"
                                       href="{{ url_for("auth.logout") }}">{{ render_icon('box-arrow-right') }}&nbsp;Logout</a>
                            {% else %}
                                <li><a class="dropdown-item"
                                       href="{{ url_for("auth.login") }}">{{ render_icon('box-arrow-in-right') }}&nbsp;Login</a>
                                </li>
                                <li><a class="dropdown-item"
                                       href="{{ url_for("auth.register") }}">{{ render_icon('person-plus') }}&nbsp;Criar conta</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
{% endmacro %}

moviedb/templates/utils.jinja2
{% macro render_messages1() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <ul class="flashes">
                {% for category, message in messages %}
                    <li class="{{ category }}">{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
{% endmacro %}

{% macro render_messages() %}
    {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            {% for category, message in messages %}
                <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                  <strong>MovieDB!</strong> {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            {% endfor %}
        {% endif %}
    {% endwith %}
{% endmacro %}